import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "@/lib/query-client-provider";
import SessionProvider from "@/lib/session-provider";
import ThemeProvider from "@/app/_common/components/theme_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
        <QueryClientProvider>
          <SessionProvider>
            {children}
          </SessionProvider>
        </QueryClientProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
